# Ctrl+Space as prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# 1 index
set -g base-index 1
setw -g pane-base-index 1

setw -g monitor-activity on
set -g visual-activity off

# Disable [Esc] delay
set -sg escape-time 0

# Pane splitting.
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Statusbar styling (atualizado para tmux 2.9+)
set -g status-style "bg=colour239"
set -g message-command-style "fg=colour235,bg=colour243"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g pane-active-border-style "fg=colour243"
set -g message-style "fg=colour235,bg=colour243"
set -g status-right-length "100"
set -g pane-border-style "fg=colour239"
setw -g window-status-style "fg=colour246,bg=colour239,bold"
setw -g window-status-activity-style "fg=colour246,bg=colour239"
setw -g window-status-separator ""
set -g status-left "#[fg=colour243,bg=colour235,bold] #S #[fg=colour235,bg=colour239,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour243,bg=colour239,nobold,nounderscore,noitalics]#[fg=colour235,bg=colour243,bold] %Y-%m-%d  %H:%M #[fg=colour235,bg=colour243,nobold,nounderscore,noitalics]#[fg=colour243,bg=colour235,bold] #h "
setw -g window-status-format "#[fg=colour246,bg=colour239,bold] #I #[fg=colour246,bg=colour239,bold] #W "
setw -g window-status-current-format "#[fg=colour239,bg=colour243,nobold,nounderscore,noitalics]#[fg=colour235,bg=colour243,bold] #I #[fg=colour235,bg=colour243,bold] #W #[fg=colour243,bg=colour239,nobold,nounderscore,noitalics]"