#!/bin/bash
for repo in $(ls -d */); do
    if [ -d $repo/.git ]; then
        git="git --git-dir=$repo/.git --work-tree=$repo/"
        $git fetch --all --quiet
        changes=$($git status --porcelain)
         [ "$changes" != "" ] && echo $repo
    fi
done

