#!/bin/bash

for repo in $(ls -d */); do
    if [ -d $repo/.git ]; then
        changes=$(git --git-dir=$repo/.git --work-tree=$repo/ status --porcelain)
        if [ "$changes" != "" ]; then
            echo $repo
        fi
    fi
done

